export enum GAME_STATUS {
  CREATED = "CREATED",
  STARTED = "STARTED",
  ROUND_IN_PROGRESS = "ROUND_IN_PROGRESS",
  ROUND_COMPLETED = "ROUND_COMPLETED",
  COMPLETED = "COMPLETED",
}

export enum ROUND_STATUS {
  NOT_STARTED = "NOT_STARTED",
  STARTED = "STARTED",
  COMPLETED = "COMPLETED",
}
