version: "3.8"
services:
  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis_instance
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
