name: Deploy Nodejs Application

on:
  push:
    branches:
      - main
    paths:
      - "server/**" # Only trigger when changes are made in the server directory

jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

        # add env variables here
        #   - name: Create .env file
        #     run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile
          push: true
          tags: riteshsp2000/judgment-card-game-server:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull riteshsp2000/judgment-card-game-server:latest

      - name: Delete old container
        run: docker rm -f nodejs-app-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name nodejs-app-container riteshsp2000/judgment-card-game-server
